import { layout, html, esc, profileData, safeJsonArray } from "../_lib.js";

function renderProfile(p){
  const photo=p.photo_url?`<img class="profile-photo" src="${esc(p.photo_url)}" alt="${esc(p.full_name)}" loading="eager">`:`<div class="profile-placeholder" aria-hidden="true">${esc((p.full_name||'L').trim().charAt(0).toUpperCase())}</div>`;
  const areas=safeJsonArray(p.practice_areas_json).map(x=>`<span class="profile-chip">${esc(x)}</span>`).join('')||'<span class="profile-chip">Not specified</span>';
  const courts=safeJsonArray(p.courts_json).map(x=>`<span class="profile-chip">${esc(x)}</span>`).join('')||'<span class="profile-chip">Not specified</span>';
  const links=[]; if(p.professional_website) links.push(`<a href="${esc(p.professional_website)}" target="_blank" rel="noopener noreferrer nofollow">Professional Website ↗</a>`); if(p.linkedin_url) links.push(`<a href="${esc(p.linkedin_url)}" target="_blank" rel="noopener noreferrer nofollow">LinkedIn ↗</a>`);
  const initials=esc((p.full_name||'L').replace(/\s+/g,' ').trim().charAt(0).toUpperCase());
  const person={"@type":"Person","name":p.full_name,"jobTitle":"Advocate","worksFor":{"@type":"Organization","name":"Lex Talk Legal"}};
  if(p.professional_website||p.linkedin_url) person.sameAs=[...([p.professional_website,p.linkedin_url].filter(Boolean))];
  const schema={"@context":"https://schema.org","@type":"ProfilePage","dateModified":p.updated_at,"mainEntity":person};
  return `<main class="profile-page"><div class="profile-hero">${photo}<div><div class="profile-kicker">LEGAL PROFESSIONAL PROFILE</div><h1 class="profile-title">${esc(p.full_name)}</h1><div class="profile-subtitle">${esc(p.designation)} · ${esc(p.city)}, ${esc(p.state)}</div><span class="profile-badge">Profile Reviewed</span></div></div><div class="profile-grid"><div><section class="profile-card"><h2>Professional Information</h2><div class="profile-list"><div class="profile-item"><div class="profile-label">State Bar Council</div><div class="profile-value">${esc(p.state_bar_council)}</div></div><div class="profile-item"><div class="profile-label">Enrolment Number</div><div class="profile-value">${esc(p.enrolment_number)}</div></div><div class="profile-item"><div class="profile-label">Year of Enrolment</div><div class="profile-value">${p.enrolment_year?esc(p.enrolment_year):'—'}</div></div><div class="profile-item"><div class="profile-label">Qualification</div><div class="profile-value">${esc(p.qualification)}</div></div></div></section><section class="profile-card"><h2>Areas of Professional Practice</h2><div class="profile-chips">${areas}</div></section><section class="profile-card"><h2>Courts / Forums</h2><div class="profile-chips">${courts}</div></section><section class="profile-card"><h2>Professional Overview</h2><div class="profile-bio">${esc(p.bio)}</div></section></div><aside><section class="profile-card"><h2>Professional Links</h2><div class="profile-links">${links.join('')||'<div class="profile-help">No external professional links have been provided for publication.</div>'}</div></section><section class="profile-card"><h2>Important Notice</h2><div class="profile-disclaimer">This profile is published for informational and professional-networking purposes. Publication does not constitute endorsement, recommendation, certification, legal advice, solicitation, lead generation, or a guarantee of result. Information is submitted by the profile holder and should be independently verified.</div></section><a class="ghost-button" href="/advocates/">← Back to Advocate Profiles</a></aside></div><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></main>`;
}

export async function onRequestGet(context){
  if(!context.env.DB) return html(layout('Advocate Profile','Legal professional profile on Lex Talk Legal.',`<main class="profile-page"><div class="notice">The professional profile database is not configured yet.</div><a class="ghost-button" href="/advocates/">Back to Legal Professionals</a></main>`,'https://lextalk.legal/advocates/'));
  const slug=String(context.params.slug||'').toLowerCase().replace(/[^a-z0-9-]/g,'').slice(0,90); if(!slug) return new Response('Not Found',{status:404});
  const row=await context.env.DB.prepare(`SELECT * FROM profiles WHERE slug=? AND status='approved' LIMIT 1`).bind(slug).first();
  if(!row) return html(layout('Profile Not Found','The requested legal professional profile was not found on Lex Talk Legal.',`<main class="profile-page"><div class="notice"><b>Profile not found.</b> The profile may be pending review, unpublished or no longer available.</div><a class="ghost-button" href="/advocates/">Browse Legal Professionals</a></main>`,'https://lextalk.legal/advocates/'),404);
  const title=`${row.full_name} | Advocate Profile`;
  const desc=`Informational professional profile of ${row.full_name}, Advocate, ${row.city}, ${row.state}.`; return html(layout(title,desc,renderProfile(row),`https://lextalk.legal/advocates/${encodeURIComponent(row.slug)}/`));
}
