import { layout, html, esc, safeJsonArray } from "../_lib.js";

const content = (profiles,count,q) => {
  const cards=profiles.map(p=>`<article class="directory-card"><div class="directory-initial">${esc((p.full_name||'L').trim().charAt(0).toUpperCase())}</div><div class="role">Advocate · ${esc(p.state_bar_council)}</div><h2>${esc(p.full_name)}</h2><div class="location">${esc(p.city)}, ${esc(p.state)}</div><p class="summary">${esc((p.bio||'').slice(0,220))}${(p.bio||'').length>220?'…':''}</p><a class="profile-open" href="/advocates/${encodeURIComponent(p.slug)}">View Professional Profile ↗</a></article>`).join('');
  return `<main class="profile-page"><div class="utility-kicker">LEGAL PROFESSIONAL COMMUNITY</div><h1>Advocate Profiles</h1><p class="lead">Free informational professional profiles published by Lex Talk Legal after administrative review. This directory does not rank, recommend or endorse advocates.</p><div class="notice"><b>Profile information:</b> Information is submitted by the respective profile holder and reviewed for publication. Publication does not constitute endorsement, recommendation, certification, legal advice, solicitation or a guarantee of outcome.</div><div class="directory-toolbar"><form method="get" style="display:flex;gap:10px;flex:1;flex-wrap:wrap"><input name="q" value="${esc(q)}" placeholder="Search name, city, state or practice area" aria-label="Search advocate profiles"><button class="cta-button" type="submit">Search</button></form><a class="ghost-button" href="/advocates/apply.html">Create Free Profile</a></div><div class="section-head"><h2>${count} Published Profile${count===1?'':'s'}</h2></div>${cards?`<div class="directory-grid">${cards}</div>`:`<div class="empty">${q?'No published profiles matched your search.':'No profiles have been published yet. Be among the first to submit a free profile.'}</div>`}<div class="profile-disclaimer" style="margin-top:25px">Lex Talk Legal does not offer paid placement, paid ranking, star ratings, guaranteed leads or “best lawyer” labels in this directory. Users should independently verify professional credentials and suitability.</div></main>`;
};

export async function onRequestGet(context){
  if(!context.env.DB) return html(layout('Advocate Profiles','Free informational advocate profiles and legal professional community on Lex Talk Legal.',content([],0,''), 'https://lextalk.legal/advocates/').replace('<main class="profile-page">','<main class="profile-page"><div class="notice">The professional profile database is being configured. Profile submission will open after the secure database and administrator controls are activated.</div>'),200);
  const url=new URL(context.request.url); const q=(url.searchParams.get('q')||'').trim().slice(0,80);
  let query=`SELECT slug,full_name,designation,state_bar_council,city,state,bio FROM profiles WHERE status='approved'`;const binds=[];if(q){query+=` AND (full_name LIKE ? OR city LIKE ? OR state LIKE ? OR practice_areas_json LIKE ?)`;const like=`%${q}%`;binds.push(like,like,like,like);}query+=' ORDER BY published_at DESC, full_name ASC LIMIT 60';
  const rows=await context.env.DB.prepare(query).bind(...binds).all();
  let cq=`SELECT COUNT(*) AS count FROM profiles WHERE status='approved'`;const cb=[];if(q){cq+=` AND (full_name LIKE ? OR city LIKE ? OR state LIKE ? OR practice_areas_json LIKE ?)`;const like=`%${q}%`;cb.push(like,like,like,like);}const c=await context.env.DB.prepare(cq).bind(...cb).first();
  return html(layout('Advocate Profiles','Free informational advocate profiles and legal professional community on Lex Talk Legal.',content(rows.results||[],Number(c?.count||0),q),'https://lextalk.legal/advocates/'));
}
